# fly.toml app configuration file generated for dhg-reactivities on 2023-12-26T14:05:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dhg-reactivities"
primary_region = "yyz"

[build]
  image = "dhgiang/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dzuua8gbj"
  Cloudinary__ApiKey="228299814819835"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
